# Generated by Django 6.1.1 on 2026-10-06 13:31

import secrets

from django.db import migrations, models


def generate_missing_barcodes(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    for user in CustomUser.objects.filter(barcode_number__in=['', None]):
        while True:
            barcode = f"USR-{secrets.token_hex(6).upper()}"
            if not CustomUser.objects.filter(barcode_number=barcode).exists():
                user.barcode_number = barcode
                user.save(update_fields=['barcode_number'])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_address_customuser_postcode'),
    ]

    operations = [
        migrations.RunPython(generate_missing_barcodes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customuser',
            name='barcode_number',
            field=models.CharField(blank=True, default='', max_length=80, unique=True),
        ),
    ]
